Implemented autoformatting on save
danreeves/sublime-prettier pull request #9
Opened 2017-01-14 15:20 UTC by adriantoine

Hi,

This allows to autoformat on save, and I added some documentation.
Fixes https://github.com/danreeves/sublime-prettier/issues/8

Let me know what you think!

Thanks

2017-01-14 15:29 UTC, adriantoine commented
mmmh actually it doesn't work, looked a bit too easy 🤔

2017-01-14 16:11 UTC, danreeves commented
Hey @adriantoine 

Thanks for the the PR. Are you sure it doesn't work because it looks correct to me. I'll try it later and let you know.

I'd love to help you get a PR merged 😀

2017-01-22 12:44 UTC, adriantoine commented
Hi @danreeves,

Thanks for your help! Sorry I didn't have time to work on that, the issue is that it was reformatting the code before saving. The plugin was running `prettier` on the unsaved file, which means that it would reformat the code before you changed it, so you would lose all the changes you made to the file.

I don't know if it's clear, I tried `on_post_save` as well, but it wouldn't save the `prettier` changes then. I'd be happy to look into it.

PS: What happened to the issues on this repo?

2017-01-22 13:10 UTC, danreeves commented
There's another plugin, but it does things in a way I don't really like. I'll try to take a look at this today. For a start the settings you added to the README should be in JSON, since that's how it's handled by Sublime.

Thanks

2017-01-22 13:11 UTC, danreeves requested changes

2017-01-22 13:11 UTC, danreeves commented on README.md
> +```js
These options should be shown in JSON

2017-01-22 13:16 UTC, adriantoine commented on README.md
> +```js
I agree but the GitHub syntax highlight is being weird with comments and show red boxes.

2017-01-22 13:19 UTC, adriantoine commented
Ok thanks, I'll see if I can fix it myself

2017-01-22 13:28 UTC, danreeves commented
You'll also need to add the default autoformat setting in `Prettier.sublime-settings`. I would prefer if autoformatting was opt-in, so default to `false`.

2017-01-22 13:29 UTC, adriantoine commented
Ok no problem, I'll add it

2017-01-22 13:33 UTC, danreeves commented on README.md
> +```js
Good point. I think it'll be fine if it still uses js highlighting but is JSON. e.g.:

```js
{
  // Comments are allowed in JS
  "printWidth": 80,
  // But not allowed in JSON
  "tabWidth": 2,
  "useFlowParser": false,
  "singleQuote": false,
  "trailingComma": false,
  "bracketSpacing": true
}
```

I _think_ Sublime handles comments anyway. Could be wrong though

2017-01-22 13:59 UTC, adriantoine commented on prettier.py
> +import platform
I don't why this is shown as a change, it's already like that in your repo: https://github.com/danreeves/sublime-prettier/blob/master/prettier.py

2017-01-22 14:00 UTC, adriantoine commented on prettier.py
> +
Same here

2017-01-22 14:06 UTC, adriantoine commented on prettier.py
> +import platform
Yeah the issue is just that I didn't merge the latest changes into my fork

2017-01-22 14:14 UTC, adriantoine commented
Hey @danreeves,

I have finally found a way to make it work, but I have changed the way the `prettier` command works.

Before, running the `prettier` command was running the `prettier` executable on the current file, which worked fine, except that it couldn't work with `on_pre_save` because it would format the code before saving and the user would lose his unsaved changes.

What I did is that instead of running the `prettier` command on the file, I run it with `--stdin` set to the whole file content, exactly the way it is done for the `prettier_selection` command, except that instead of formatting the selection, I format the whole file. In that way, you can format the whole file, even the unsaved changes.

So I created the `prettify_code` function which formats and replaces a given `Region`.

Let me know what you think!

2017-01-22 14:15 UTC, danreeves commented
This is awesome, I had been planning on refactoring the two commands to work the same. Nice work!

I'm going to pull it down now and give it a go

2017-01-22 14:17 UTC, adriantoine commented
Great, thanks!

2017-01-22 14:30 UTC, danreeves requested changes
Amazing PR! Seems to work perfectly, just a few little things and I'll merge it.

2017-01-22 14:30 UTC, danreeves commented on README.md
> +  autoformat: true,
Can you add double quotes around the keys here, so it looks like JSON.

2017-01-22 14:30 UTC, danreeves commented on prettier.py
> +# Calls prettier on the given region and replaces code
Two empty lines above function defs please. It's not written anywhere yet but the project is following flake8 linting rules.

2017-01-22 14:30 UTC, danreeves commented on prettier.py
>              text = self.view.substr(region)
`text` isn't used here so this line can be removed

2017-01-22 14:30 UTC, danreeves commented on prettier.py
>          command = ['prettier'] + options + ['--stdin']
`command` isn't used here so this line can be removed

2017-01-22 14:30 UTC, danreeves commented on prettier.py
> +        if autoformat == True:
should be `if autoformat is True:` according to the flake8 linter

2017-01-22 14:35 UTC, danreeves approved these changes

2017-01-22 14:35 UTC, adriantoine commented
Thanks for the review! I'm not a Python developer so I wasn't aware of the style recommendations, it's all fixed now.

2017-01-22 14:41 UTC, merged

2017-01-22 14:42 UTC, danreeves commented
Not a problem. Thanks so much @adriantoine

2017-01-22 14:43 UTC, adriantoine commented
No problem, thank you @danreeves